logo = true
logoText = "Bootcamp"
logoType = "short" # long, short
description = "Protocolli e Archivio eventi"
themeOptions = ["light", "dark"]

useFaviconGenerator = true

wideViewAsDefault = true

enableWideBlogSwitch = true
enableTocSwitch = false
enableLandingBackground = true
enableSearch = true
enableSearchHighlight = true
enableLangChange = false
enableDarkMode = true
enableBreadcrumb = true
enableBlogBreadcrumb = true
enableEditBtn = false
enableToc = false
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = true

paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

github = "https://github.com/xpy5/ARE"

enableComment = false
